name: Deploy to Amazon ECS

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: Run a one liner
       run: echo Hello, WORLD!
     
      -name: Run a multi line script
       run: 
        echo Add other actions to build
        echo test, and deploy your project
